// ignore_for_file: equal_keys_in_map

import 'package:weather_icons/weather_icons.dart';

const Map weatherIcons = {
  'Sunny': WeatherIcons.day_sunny,
  'Clear ': WeatherIcons.night_clear,
  'Clear': WeatherIcons.night_clear,
  'Cloudy': WeatherIcons.cloudy,
  'Partly Cloudy ': WeatherIcons.day_cloudy,
  'Partly Cloudy': WeatherIcons.day_cloudy,
  'Partly cloudy': WeatherIcons.day_cloudy,
  'Rainy': WeatherIcons.rain,
  'Light drizzle': WeatherIcons.rain_mix,
  'Showers': WeatherIcons.showers,
  'Thunderstorms': WeatherIcons.thunderstorm,
  'Snowy': WeatherIcons.snow,
  'Foggy': WeatherIcons.fog,
  'Fog': WeatherIcons.fog,
  'Windy': WeatherIcons.wind,
  'Hazy': WeatherIcons.day_haze,
  'Light rain': WeatherIcons.rain_mix,
  'Overcast ': WeatherIcons.day_cloudy,
  'Overcast': WeatherIcons.day_cloudy,
  'Patchy rain nearby': WeatherIcons.rain_wind,
  'Mist': WeatherIcons.fog,
  'error': WeatherIcons.alien,
};

List<String> cities = [
  'Abidjan',
  'Abu Dhabi',
  'Abuja',
  'Accra',
  'Addis Ababa',
  'Ahmedabad',
  'Aleppo',
  'Alexandria',
  'Algiers',
  'Almaty',
  'Amman',
  'Amsterdam',
  'Anchorage',
  'Andorra la Vella',
  'Ankara',
  'Antananarivo',
  'Apia',
  'Arnold',
  'Ashgabat',
  'Asmara',
  'Asuncion',
  'Athens',
  'Auckland',
  'Avarua',
  'Baghdad',
  'Baku',
  'Bamako',
  'Banda Aceh',
  'Bandar Seri Begawan',
  'Bandung',
  'Bangkok',
  'Bangui',
  'Banjul',
  'Barcelona',
  'Barranquilla',
  'Basrah',
  'Basse-Terre',
  'Basseterre',
  'Beijing',
  'Beirut',
  'Bekasi',
  'Belem',
  'Belgrade',
  'Belmopan',
  'Belo Horizonte',
  'Bengaluru',
  'Berlin',
  'Bern',
  'Bishkek',
  'Bissau',
  'Bogota',
  'Brasilia',
  'Bratislava',
  'Brazzaville',
  'Bridgetown',
  'Brisbane',
  'Brussels',
  'Bucharest',
  'Budapest',
  'Buenos Aires',
  'Bujumbura',
  'Bursa',
  'Busan',
  'Cairo',
  'Cali',
  'Caloocan',
  'Camayenne',
  'Canberra',
  'Cape Town',
  'Caracas',
  'Casablanca',
  'Castries',
  'Cayenne',
  'Charlotte Amalie',
  'Chengdu',
  'Chennai',
  'Chicago',
  'Chisinau',
  'Chittagong',
  'Chongqing',
  'Colombo',
  'Conakry',
  'Copenhagen',
  'Cordoba',
  'Curitiba',
  'Daegu',
  'Daejeon',
  'Dakar',
  'Dallas',
  'Damascus',
  'Dar es Salaam',
  'Delhi',
  'Denver',
  'Dhaka',
  'Dili',
  'Djibouti',
  'Dodoma',
  'Doha',
  'Dongguan',
  'Douala',
  'Douglas',
  'Dubai',
  'Dublin',
  'Durban',
  'Dushanbe',
  'Faisalabad',
  'Fort-de-France',
  'Fortaleza',
  'Freetown',
  'Fukuoka',
  'Funafuti',
  'Gaborone',
  'George Town',
  'Georgetown',
  'Gibraltar',
  'Gitega',
  'Giza',
  'Guadalajara',
  'Guangzhou',
  'Guatemala City',
  'Guayaquil',
  'Gujranwala',
  'Gustavia',
  'Gwangju',
  'Hamburg',
  'Hanoi',
  'Harare',
  'Havana',
  'Helsinki',
  'Ho Chi Minh City',
  'Hong Kong',
  'Honiara',
  'Honolulu',
  'Houston',
  'Hyderabad',
  'Hyderabad',
  'Ibadan',
  'Incheon',
  'Isfahan',
  'Islamabad',
  'Istanbul',
  'Izmir',
  'Jaipur',
  'Jakarta',
  'Jeddah',
  'Jerusalem',
  'Johannesburg',
  'Juarez',
  'Juba',
  'Kabul',
  'Kaduna',
  'Kampala',
  'Kano',
  'Kanpur',
  'Kaohsiung',
  'Karachi',
  'Karaj',
  'Kathmandu',
  'Kawasaki',
  'Kharkiv',
  'Khartoum',
  'Khulna',
  'Kigali',
  'Kingsburg',
  'Kingston',
  'Kingstown',
  'Kinshasa',
  'Kobe',
  'Kolkata',
  'Kota Bharu',
  'Kowloon',
  'Kuala Lumpur',
  'Kumasi',
  'Kuwait',
  'Kyiv',
  'Kyoto',
  'La Paz',
  'Lagos',
  'Lahore',
  'Libreville',
  'Lilongwe',
  'Lima',
  'Lisbon',
  'Ljubljana',
  'Lome',
  'London',
  'Los Angeles',
  'Luanda',
  'Lubumbashi',
  'Lusaka',
  'Luxembourg',
  'Macau',
  'Madrid',
  'Majuro',
  'Makassar',
  'Malabo',
  'Male',
  'Mamoudzou',
  'Managua',
  'Manama',
  'Manaus',
  'Manila',
  'Maputo',
  'Maracaibo',
  'Maracay',
  'Mariehamn',
  'Marigot',
  'Maseru',
  'Mashhad',
  'Mbabane',
  'Mecca',
  'Medan',
  'Medellin',
  'Medina',
  'Melbourne',
  'Mexico City',
  'Miami',
  'Minsk',
  'Mogadishu',
  'Monaco',
  'Monrovia',
  'Montevideo',
  'Montreal',
  'Moroni',
  'Moscow',
  'Mosul',
  'Multan',
  'Mumbai',
  'Muscat',
  'N\'Djamena',
  'Nagoya',
  'Nairobi',
  'Nanchong',
  'Nanjing',
  'Nassau',
  'Nay Pyi Taw',
  'New York',
  'Niamey',
  'Nicosia',
  'Nouakchott',
  'Noumea',
  'Novosibirsk',
  'Nuku\'alofa',
  'Nur-Sultan',
  'Nuuk',
  'Oranjestad',
  'Osaka',
  'Oslo',
  'Ottawa',
  'Ouagadougou',
  'Pago Pago',
  'Palembang',
  'Palo Alto',
  'Panama',
  'Papeete',
  'Paramaribo',
  'Paris',
  'Perth',
  'Philadelphia',
  'Phnom Penh',
  'Phoenix',
  'Podgorica',
  'Port Louis',
  'Port Moresby',
  'Port of Spain',
  'Port-Vila',
  'Port-au-Prince',
  'Porto Alegre',
  'Porto-Novo',
  'Prague',
  'Praia',
  'Pretoria',
  'Pristina',
  'Puebla',
  'Pune',
  'Pyongyang',
  'Quezon City',
  'Quito',
  'Rabat',
  'Rawalpindi',
  'Recife',
  'Reykjavik',
  'Riga',
  'Rio de Janeiro',
  'Riyadh',
  'Road Town',
  'Rome',
  'Roseau',
  'Saint George\'s',
  'Saint Helier',
  'Saint John\'s',
  'Saint Peter Port',
  'Saint Petersburg',
  'Saint-Denis',
  'Saint-Pierre',
  'Saipan',
  'Salvador',
  'San Antonio',
  'San Diego',
  'San Francisco',
  'San Jose',
  'San Juan',
  'San Marino',
  'San Salvador',
  'Sanaa',
  'Santa Cruz de la Sierra',
  'Santiago',
  'Santo Domingo',
  'Sao Paulo',
  'Sao Tome',
  'Sapporo',
  'Sarajevo',
  'Seattle',
  'Semarang',
  'Seoul',
  'Shanghai',
  'Sharjah',
  'Shenzhen',
  'Singapore',
  'Skopje',
  'Sofia',
  'South Tangerang',
  'Soweto',
  'Stockholm',
  'Sucre',
  'Surabaya',
  'Surat',
  'Suva',
  'Sydney',
  'Tabriz',
  'Taipei',
  'Tallinn',
  'Tangerang',
  'Tarawa',
  'Tashkent',
  'Tbilisi',
  'Tegucigalpa',
  'Tehran',
  'Tel Aviv',
  'Thimphu',
  'Tianjin',
  'Tijuana',
  'Tirana',
  'Tokyo',
  'Toronto',
  'Torshavn',
  'Tripoli',
  'Tunis',
  'Ulan Bator',
  'Vaduz',
  'Valencia',
  'Valletta',
  'Vancouver',
  'Victoria',
  'Vienna',
  'Vientiane',
  'Vilnius',
  'Warsaw',
  'Washington',
  'Wellington',
  'Willemstad',
  'Windhoek',
  'Wuhan',
  'Xi\'an',
  'Yamoussoukro',
  'Yangon',
  'Yaounde',
  'Yekaterinburg',
  'Yerevan',
  'Yokohama',
  'Zagreb'
];

Map<String, String> citiesCountries = {
  'Abidjan': 'Ivory Coast',
  'Abu Dhabi': 'United Arab Emirates',
  'Abuja': 'Nigeria',
  'Accra': 'Ghana',
  'Addis Ababa': 'Ethiopia',
  'Ahmedabad': 'India',
  'Aleppo': 'Syria',
  'Alexandria': 'Egypt',
  'Algiers': 'Algeria',
  'Almaty': 'Kazakhstan',
  'Amman': 'Jordan',
  'Amsterdam': 'Netherlands',
  'Anchorage': 'United States',
  'Andorra la Vella': 'Andorra',
  'Ankara': 'Turkey',
  'Antananarivo': 'Madagascar',
  'Apia': 'Samoa',
  'Arnold': 'United States',
  'Ashgabat': 'Turkmenistan',
  'Asmara': 'Eritrea',
  'Asuncion': 'Paraguay',
  'Athens': 'Greece',
  'Auckland': 'New Zealand',
  'Avarua': 'Cook Islands',
  'Baghdad': 'Iraq',
  'Baku': 'Azerbaijan',
  'Bamako': 'Mali',
  'Banda Aceh': 'Indonesia',
  'Bandar Seri Begawan': 'Brunei',
  'Bandung': 'Indonesia',
  'Bangkok': 'Thailand',
  'Bangui': 'Central African Republic',
  'Banjul': 'Gambia',
  'Barcelona': 'Spain',
  'Barranquilla': 'Colombia',
  'Basrah': 'Iraq',
  'Basse-Terre': 'Guadeloupe',
  'Basseterre': 'Saint Kitts and Nevis',
  'Beijing': 'China',
  'Beirut': 'Lebanon',
  'Bekasi': 'Indonesia',
  'Belem': 'Brazil',
  'Belgrade': 'Serbia',
  'Belmopan': 'Belize',
  'Belo Horizonte': 'Brazil',
  'Bengaluru': 'India',
  'Berlin': 'Germany',
  'Bern': 'Switzerland',
  'Bishkek': 'Kyrgyzstan',
  'Bissau': 'Guinea-Bissau',
  'Bogota': 'Colombia',
  'Brasilia': 'Brazil',
  'Bratislava': 'Slovakia',
  'Brazzaville': 'Republic of the Congo',
  'Bridgetown': 'Barbados',
  'Brisbane': 'Australia',
  'Brussels': 'Belgium',
  'Bucharest': 'Romania',
  'Budapest': 'Hungary',
  'Buenos Aires': 'Argentina',
  'Bujumbura': 'Burundi',
  'Bursa': 'Turkey',
  'Busan': 'South Korea',
  'Cairo': 'Egypt',
  'Cali': 'Colombia',
  'Caloocan': 'Philippines',
  'Camayenne': 'Guinea',
  'Canberra': 'Australia',
  'Cape Town': 'South Africa',
  'Caracas': 'Venezuela',
  'Casablanca': 'Morocco',
  'Castries': 'Saint Lucia',
  'Cayenne': 'French Guiana',
  'Charlotte Amalie': 'U.S. Virgin Islands',
  'Chengdu': 'China',
  'Chennai': 'India',
  'Chicago': 'United States',
  'Chisinau': 'Moldova',
  'Chittagong': 'Bangladesh',
  'Chongqing': 'China',
  'Colombo': 'Sri Lanka',
  'Conakry': 'Guinea',
  'Copenhagen': 'Denmark',
  'Cordoba': 'Argentina',
  'Curitiba': 'Brazil',
  'Daegu': 'South Korea',
  'Daejeon': 'South Korea',
  'Dakar': 'Senegal',
  'Dallas': 'United States',
  'Damascus': 'Syria',
  'Dar es Salaam': 'Tanzania',
  'Delhi': 'India',
  'Denver': 'United States',
  'Dhaka': 'Bangladesh',
  'Dili': 'Timor Leste',
  'Djibouti': 'Djibouti',
  'Dodoma': 'Tanzania',
  'Doha': 'Qatar',
  'Dongguan': 'China',
  'Douala': 'Cameroon',
  'Douglas': 'Isle of Man',
  'Dubai': 'United Arab Emirates',
  'Dublin': 'Ireland',
  'Durban': 'South Africa',
  'Dushanbe': 'Tajikistan',
  'Faisalabad': 'Pakistan',
  'Fort-de-France': 'Martinique',
  'Fortaleza': 'Brazil',
  'Freetown': 'Sierra Leone',
  'Fukuoka': 'Japan',
  'Funafuti': 'Tuvalu',
  'Gaborone': 'Botswana',
  'George Town': 'Malaysia',
  'Georgetown': 'Guyana',
  'Gibraltar': 'Gibraltar',
  'Gitega': 'Burundi',
  'Giza': 'Egypt',
  'Guadalajara': 'Mexico',
  'Guangzhou': 'China',
  'Guatemala City': 'Guatemala',
  'Guayaquil': 'Ecuador',
  'Gujranwala': 'Pakistan',
  'Gustavia': 'Saint Barthelemy',
  'Gwangju': 'South Korea',
  'Hamburg': 'Germany',
  'Hanoi': 'Vietnam',
  'Harare': 'Zimbabwe',
  'Havana': 'Cuba',
  'Helsinki': 'Finland',
  'Ho Chi Minh City': 'Vietnam',
  'Hong Kong': 'Hong Kong',
  'Honiara': 'Solomon Islands',
  'Honolulu': 'United States',
  'Houston': 'United States',
  'Hyderabad': 'India',
  'Hyderabad': 'Pakistan',
  'Ibadan': 'Nigeria',
  'Incheon': 'South Korea',
  'Isfahan': 'Iran',
  'Islamabad': 'Pakistan',
  'Istanbul': 'Turkey',
  'Izmir': 'Turkey',
  'Jaipur': 'India',
  'Jakarta': 'Indonesia',
  'Jeddah': 'Saudi Arabia',
  'Jerusalem': 'Israel',
  'Johannesburg': 'South Africa',
  'Juarez': 'Mexico',
  'Juba': 'South Sudan',
  'Kabul': 'Afghanistan',
  'Kaduna': 'Nigeria',
  'Kampala': 'Uganda',
  'Kano': 'Nigeria',
  'Kanpur': 'India',
  'Kaohsiung': 'Taiwan',
  'Karachi': 'Pakistan',
  'Karaj': 'Iran',
  'Kathmandu': 'Nepal',
  'Kawasaki': 'Japan',
  'Kharkiv': 'Ukraine',
  'Khartoum': 'Sudan',
  'Khulna': 'Bangladesh',
  'Kigali': 'Rwanda',
  'Kingsburg': 'United States',
  'Kingston': 'Jamaica',
  'Kingstown': 'Saint Vincent and the Grenadines',
  'Kinshasa': 'Democratic Republic of the Congo',
  'Kobe': 'Japan',
  'Kolkata': 'India',
  'Kota Bharu': 'Malaysia',
  'Kowloon': 'Hong Kong',
  'Kuala Lumpur': 'Malaysia',
  'Kumasi': 'Ghana',
  'Kuwait': 'Kuwait',
  'Kyiv': 'Ukraine',
  'Kyoto': 'Japan',
  'La Paz': 'Bolivia',
  'Lagos': 'Nigeria',
  'Lahore': 'Pakistan',
  'Libreville': 'Gabon',
  'Lilongwe': 'Malawi',
  'Lima': 'Peru',
  'Lisbon': 'Portugal',
  'Ljubljana': 'Slovenia',
  'Lome': 'Togo',
  'London': 'United Kingdom',
  'Los Angeles': 'United States',
  'Luanda': 'Angola',
  'Lubumbashi': 'Democratic Republic of the Congo',
  'Lusaka': 'Zambia',
  'Luxembourg': 'Luxembourg',
  'Macau': 'Macao',
  'Madrid': 'Spain',
  'Majuro': 'Marshall Islands',
  'Makassar': 'Indonesia',
  'Malabo': 'Equatorial Guinea',
  'Male': 'Maldives',
  'Mamoudzou': 'Mayotte',
  'Managua': 'Nicaragua',
  'Manama': 'Bahrain',
  'Manaus': 'Brazil',
  'Manila': 'Philippines',
  'Maputo': 'Mozambique',
  'Maracaibo': 'Venezuela',
  'Maracay': 'Venezuela',
  'Mariehamn': 'Aland Islands',
  'Marigot': 'Saint Martin',
  'Maseru': 'Lesotho',
  'Mashhad': 'Iran',
  'Mbabane': 'Eswatini',
  'Mecca': 'Saudi Arabia',
  'Medan': 'Indonesia',
  'Medellin': 'Colombia',
  'Medina': 'Saudi Arabia',
  'Melbourne': 'Australia',
  'Mexico City': 'Mexico',
  'Miami': 'United States',
  'Minsk': 'Belarus',
  'Mogadishu': 'Somalia',
  'Monaco': 'Monaco',
  'Monrovia': 'Liberia',
  'Montevideo': 'Uruguay',
  'Montreal': 'Canada',
  'Moroni': 'Comoros',
  'Moscow': 'Russia',
  'Mosul': 'Iraq',
  'Multan': 'Pakistan',
  'Mumbai': 'India',
  'Muscat': 'Oman',
  'N\'Djamena': 'Chad',
  'Nagoya': 'Japan',
  'Nairobi': 'Kenya',
  'Nanchong': 'China',
  'Nanjing': 'China',
  'Nassau': 'Bahamas',
  'Nay Pyi Taw': 'Myanmar',
  'New York': 'United States',
  'Niamey': 'Niger',
  'Nicosia': 'Cyprus',
  'Nouakchott': 'Mauritania',
  'Noumea': 'New Caledonia',
  'Novosibirsk': 'Russia',
  'Nuku\'alofa': 'Tonga',
  'Nur-Sultan': 'Kazakhstan',
  'Nuuk': 'Greenland',
  'Oranjestad': 'Aruba',
  'Osaka': 'Japan',
  'Oslo': 'Norway',
  'Ottawa': 'Canada',
  'Ouagadougou': 'Burkina Faso',
  'Pago Pago': 'American Samoa',
  'Palembang': 'Indonesia',
  'Palo Alto': 'United States',
  'Panama': 'Panama',
  'Papeete': 'French Polynesia',
  'Paramaribo': 'Suriname',
  'Paris': 'France',
  'Perth': 'Australia',
  'Philadelphia': 'United States',
  'Phnom Penh': 'Cambodia',
  'Phoenix': 'United States',
  'Podgorica': 'Montenegro',
  'Port Louis': 'Mauritius',
  'Port Moresby': 'Papua New Guinea',
  'Port of Spain': 'Trinidad and Tobago',
  'Port-Vila': 'Vanuatu',
  'Port-au-Prince': 'Haiti',
  'Porto Alegre': 'Brazil',
  'Porto-Novo': 'Benin',
  'Prague': 'Czechia',
  'Praia': 'Cabo Verde',
  'Pretoria': 'South Africa',
  'Pristina': 'Kosovo',
  'Puebla': 'Mexico',
  'Pune': 'India',
  'Pyongyang': 'North Korea',
  'Quezon City': 'Philippines',
  'Quito': 'Ecuador',
  'Rabat': 'Morocco',
  'Rawalpindi': 'Pakistan',
  'Recife': 'Brazil',
  'Reykjavik': 'Iceland',
  'Riga': 'Latvia',
  'Rio de Janeiro': 'Brazil',
  'Riyadh': 'Saudi Arabia',
  'Road Town': 'British Virgin Islands',
  'Rome': 'Italy',
  'Roseau': 'Dominica',
  'Saint George\'s': 'Grenada',
  'Saint Helier': 'Jersey',
  'Saint John\'s': 'Antigua and Barbuda',
  'Saint Peter Port': 'Guernsey',
  'Saint Petersburg': 'Russia',
  'Saint-Denis': 'Reunion',
  'Saint-Pierre': 'Reunion',
  'Saipan': 'Northern Mariana Islands',
  'Salvador': 'Brazil',
  'San Antonio': 'United States',
  'San Diego': 'United States',
  'San Francisco': 'United States',
  'San Jose': 'United States',
  'San Juan': 'Argentina',
  'San Marino': 'United States',
  'San Salvador': 'El Salvador',
  'Sanaa': 'Yemen',
  'Santa Cruz de la Sierra': 'Bolivia',
  'Santiago': 'Chile',
  'Santo Domingo': 'Dominican Republic',
  'Sao Paulo': 'Brazil',
  'Sao Tome': 'Sao Tome and Principe',
  'Sapporo': 'Japan',
  'Sarajevo': 'Bosnia and Herzegovina',
  'Seattle': 'United States',
  'Semarang': 'Indonesia',
  'Seoul': 'South Korea',
  'Shanghai': 'China',
  'Sharjah': 'United Arab Emirates',
  'Shenzhen': 'China',
  'Singapore': 'Singapore',
  'Skopje': 'North Macedonia',
  'Sofia': 'Bulgaria',
  'South Tangerang': 'Indonesia',
  'Soweto': 'South Africa',
  'Stockholm': 'Sweden',
  'Sucre': 'Bolivia',
  'Surabaya': 'Indonesia',
  'Surat': 'India',
  'Suva': 'Fiji',
  'Sydney': 'Australia',
  'Tabriz': 'Iran',
  'Taipei': 'Taiwan',
  'Tallinn': 'Estonia',
  'Tangerang': 'Indonesia',
  'Tarawa': 'Kiribati',
  'Tashkent': 'Uzbekistan',
  'Tbilisi': 'Georgia',
  'Tegucigalpa': 'Honduras',
  'Tehran': 'Iran',
  'Tel Aviv': 'Israel',
  'Thimphu': 'Bhutan',
  'Tianjin': 'China',
  'Tijuana': 'Mexico',
  'Tirana': 'Albania',
  'Tokyo': 'Japan',
  'Toronto': 'Canada',
  'Torshavn': 'Faroe Islands',
  'Tripoli': 'Libya',
  'Tunis': 'Tunisia',
  'Ulan Bator': 'Mongolia',
  'Vaduz': 'Liechtenstein',
  'Valencia': 'Venezuela',
  'Valletta': 'Malta',
  'Vancouver': 'Canada',
  'Victoria': 'Canada',
  'Vienna': 'Austria',
  'Vientiane': 'Laos',
  'Vilnius': 'Lithuania',
  'Warsaw': 'Poland',
  'Washington': 'United States',
  'Wellington': 'New Zealand',
  'Willemstad': 'Curacao',
  'Windhoek': 'Namibia',
  'Wuhan': 'China',
  'Xi\'an': 'China',
  'Yamoussoukro': 'Ivory Coast',
  'Yangon': 'Myanmar',
  'Yaounde': 'Cameroon',
  'Yekaterinburg': 'Russia',
  'Yerevan': 'Armenia',
  'Yokohama': 'Japan',
  'Zagreb': 'Croatia'
};
